-- Create reviews table for vehicle reviews and ratings system
CREATE TABLE IF NOT EXISTS public.reviews
(
    review_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    inv_id integer NOT NULL,
    account_id integer NOT NULL,
    review_rating integer NOT NULL CHECK (review_rating >= 1 AND review_rating <= 5),
    review_text text,
    review_date timestamp DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT reviews_pkey PRIMARY KEY (review_id)
);

-- Create relationships
ALTER TABLE IF EXISTS public.reviews
    ADD CONSTRAINT fk_reviews_inventory FOREIGN KEY (inv_id)
    REFERENCES public.inventory (inv_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;

ALTER TABLE IF EXISTS public.reviews
    ADD CONSTRAINT fk_reviews_account FOREIGN KEY (account_id)
    REFERENCES public.account (account_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;

-- Create index for better query performance
CREATE INDEX IF NOT EXISTS idx_reviews_inv_id ON public.reviews (inv_id);
CREATE INDEX IF NOT EXISTS idx_reviews_account_id ON public.reviews (account_id);
CREATE INDEX IF NOT EXISTS idx_reviews_rating ON public.reviews (review_rating);
